# Generated by Django

from django.db import migrations, models
import re
from decimal import Decimal, InvalidOperation, ROUND_HALF_UP

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_lock', models.BooleanField(default=False)),
                ('allow_uploads', models.BooleanField(default=False)),
                ('allow_upload_deletions', models.BooleanField(default=False)),
                ('allow_email_notifications', models.BooleanField(default=False)),
                ('records_per_page', models.IntegerField(default=25, validators=[lambda x: x >= 1])),
            ],
            options={
                'verbose_name': 'Konfigurasi Aplikasi',
                'verbose_name_plural': 'Konfigurasi Aplikasi',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('sku', models.CharField(editable=True, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('purchase_price', models.DecimalField(max_digits=10, decimal_places=2)),
                ('quantity', models.IntegerField(validators=[lambda x: x >= 0])),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, to='stock_manager.item')),
                ('shop_user', models.ForeignKey(on_delete=models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'unique_together': {('shop_user', 'item')},
            },
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('ordered', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=models.deletion.CASCADE, to='stock_manager.item')),
                ('shop_user', models.ForeignKey(on_delete=models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]

