# Generated by Django

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]

