# Generated by Django 6.0.5 on 2026-06-22 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0002_add_expiry_date_and_rename_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='records_per_page',
            field=models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
